### ISSUE TITLE
investigate how to add testing to music-box-interactive

### ISSUE THREAD

**Issue by mattldawson** [NCAR/music-box-interactive#103]
https://docs.djangoproject.com/en/3.1/topics/testing/

**Comment by s-omas** [comment]
I have used [selenium](https://www.selenium.dev/) before, maybe a good option for gui testing

**Comment by mattldawson** [comment]
looks good to me. I think our most important tests will be making sure that things entered into the interface actually make it to the model, because the model ignores things it's not looking for. Do you think selenium is good for this type of test?

**Comment by s-omas** [comment]
Yes, selenium would definitely be good for making sure imputed values get handled correctly

**Comment by mattldawson** [comment]
great - would you be able to set up a simple selenium test for music-box-interactive to show us how it works?

**Comment by AndrewJConley** [comment]
It turns out that human testing gets more errors than selenium.  The tests are harder to write and maintain than doing the testing by hand.  Tests were only running in one browser.
