### ISSUE TITLE
linear combinations - several updates

### ISSUE THREAD

**Issue by mattldawson** [NCAR/music-box-interactive#108]
- the list of variables is not showing after loading a NetCDF file
- linear combinations do not appear on the evolving conditions page after being loaded
- linear combinations should be restricted to concentrations (columns starting with 'CONC.')
- need instructions for linear combinations
- need ability to add scaling factors to linear combinations

**Comment by s-omas** [comment]
#133 allows viewing  and removing of linear combinations
