### ISSUE TITLE
exp(-C/T) or exp(-Ea/T)

### ISSUE THREAD

**Issue by AndrewJConley** [NCAR/music-box-interactive#152]
right now the user interface is only showing Ea.  So temperature dependence is hidden.

We need to sort out whether we support Ea or Ea and C in the user interface.  But the data should not be hidden.

**Comment by AndrewJConley** [comment]
The user interface should not show C.  It should show either "Ea" or "Ea/R". We should remove "C" from all definitions.
@mattldawson , what do you think?

**Comment by mattldawson** [comment]
I agree, although I think it should be "Ea" or "Ea/k_B" the way it's currently set up.

**Comment by AndrewJConley** [comment]
We also need a consistency check or an automatic conversion to Ea...
If we allow both forms, then we need
- Rule denying the use of both Ea and Ea/k_B (consistency)
- UI mods to show the chosen route

Another approach: Require the underlying model to support Ea.
- The user chooses between entering Ea or Ea/k_B (use the units column?), or make the key switchable. 
- A consequence would be that the next time the user looked at the UI, Ea would be shown.

**Comment by AndrewJConley** [comment]
Or do we just insist on Ea only, and provide a calculator for Ea <-> Ea/k_B

**Comment by AndrewJConley** [comment]
Wait until testers ask for this flexibility.
