### ISSUE TITLE
User interface calculators

### ISSUE THREAD

**Issue by AndrewJConley** [NCAR/music-box-interactive#182]
Users may want some calculators to support unit conversions or other things.  What are all the different calculators that we need?  Add them to the list.
Also how might we implement these?  Where would they be accessible?  Pop ups?  From a menu item?

- Ea <-> Ea/k_B

**Comment by mattldawson** [comment]
For unit conversions, we have the units dropdown boxes where users can specify the units they want to use. But, this wouldn't work for Ea <-> Ea/k_B. Would there be many cases like Ea <-> Ea/k_B? Or is this somewhat unique?

**Comment by AndrewJConley** [comment]
Done, committed.
