### ISSUE TITLE
Add minimum plot scale to not show noise

### ISSUE THREAD

**Issue by mattldawson** [NCAR/music-box-interactive#197]
Minimum scale for plot should be 2*tolerance

**Comment by AndrewJConley** [comment]
I just had another idea, that we might simply draw a line across the plot at the convergence tolerance.  Or is that more confusing than having a minimum scale?  @mattldawson @s-omas

**Comment by mattldawson** [comment]
I'm not sure I would understand what the line meant without some explanation. I still kind of like the idea of a minimum scale - if someone was really interested in the noise, they could still download the results and plot them offline.
