### ISSUE TITLE
Confusion for users: Initial conditions vs Pressure

### ISSUE THREAD

**Issue by AndrewJConley** [NCAR/music-box-interactive#224]
When I asked a student to change the pressure for the Chapman example, they changed the value in the "Initial conditions" page, without recognizing that the data specified there is overwritten by the data in the ENV-pressure data from the "Evolving" tab.

I wonder @mattldawson @s-omas if we need a better warning for people.

Your thoughts?

**Comment by mattldawson** [comment]
We could only have evolving conditions. Initial conditions would just be evolving conditions with a single time step.

**Comment by AndrewJConley** [comment]
Moved to validation.
