### ISSUE TITLE
Convert value when changing unit?

### ISSUE THREAD

**Issue by AndrewJConley** [NCAR/music-box-interactive#227]
When I change units in the Environmental Conditions section, the value is updated.
When I change units in the Species Concentrations, the value does not change.

Do we want to do this consistently?

**Comment by s-omas** [comment]
I remember this was something we chose to do, I forget the reason.

**Comment by AndrewJConley** [comment]
Species concentrations need additional information (pv=nrt). So users will use calculator for these computations.
