### ISSUE TITLE
Troe latex formula error

### ISSUE THREAD

**Issue by AndrewJConley** [NCAR/music-box-interactive#228]
The exponent of F_c for the Troe reaction formula (latex) places the parenthesis in the wrong place.  
<img width="422" alt="Screen Shot 2021-06-02 at 10 39 16 AM" src="https://user-images.githubusercontent.com/8648491/120518436-d3232400-c38e-11eb-8369-75b2ea886fe1.png">

**Comment by mattldawson** [comment]
Hi @AndrewJConley - which parentheses did you mean? This is from FP^2:
![image](https://user-images.githubusercontent.com/13121557/120519593-a6b7d980-c387-11eb-9837-5f5a827a8381.png)

**Comment by AndrewJConley** [comment]
This is just an error in the reaction editor in the user interface.

**Comment by mattldawson** [comment]
ah, sorry - I misunderstood. The image you posted is the correct equation?

**Comment by AndrewJConley** [comment]
Yes. Your formula is correct. The GUI has misplaced left parenthesis. Thanks for helping me clarify!

Andrew
