### ISSUE TITLE
Calculator is off by several orders of magnitude

### ISSUE THREAD

**Issue by AndrewJConley** [NCAR/music-box-interactive#232]
<img width="349" alt="Screen Shot 2021-06-08 at 3 11 27 PM" src="https://user-images.githubusercontent.com/8648491/121258283-f1e05980-c86b-11eb-9975-8f30173eb56f.png">

**Comment by s-omas** [comment]
@AndrewJConley what should the correct number be?

I thought
 1 mol m-3 = 6.022e+29 molecule / cm-3

**Comment by AndrewJConley** [comment]
I always get confused on this, so let me know if I've made a mistake:

(1 mole/m3)(6.022e+23 molec/mole)(1m/100cm)^3 = 6.022e+23/1e6 molec/cm3
= 6.022e+17 molec/cm3
