### ISSUE TITLE
Use SI units in reaction editor

### ISSUE THREAD

**Issue by mattldawson** [NCAR/music-box-interactive#63]
The CAMP mechanism format expects a few rate constant parameters in # cm-3. Until CAMP is updated to use all SI units, do the conversion on the server side so that the interface uses only SI units.

**Comment by AndrewJConley** [comment]
I'd like to evaluate the UI units with the scientists.  It feels like all of the published literature is in #/cc. So I wonder if we need the flexibility in the opposite direction?

**Comment by mattldawson** [comment]
Maybe we could have selectable units, with the conversion applied by the interface?

**Comment by AndrewJConley** [comment]
I think we might get better buy-in.  There has been considerable grumbling
about our use of SI units.  But I'm very excited to have the internal model
move to all SI units.

**Comment by AndrewJConley** [comment]
User interface allows unit conversions as well as entry in numerous units
