### ISSUE TITLE
Adding a species to a reaction did not lead to changed results

### ISSUE THREAD

**Issue by AndrewJConley** [NCAR/music-box-interactive#82]
After running the model, I added He as a product of photodecomposition of O2.  [ yes, I saved the changes to the molecule and saved the changes to the reaction ]

When I click the "Run Model" button, nothing seems to happen.  The log does not show the "GET /model/run HTTP/1.1" message.

However, if I choose the Conditions menu, and "save" the Model Options, then the run works as expected.  [This is not intuitive]

And additional, related problem is that when I go back and then "delete" He from the reaction, I can't even "save" the configuration without modifing something (say simulation length).

**Comment by mattldawson** [comment]
I think this is the same as #79

**Comment by AndrewJConley** [comment]
Closed as duplicate of #79
