### ISSUE TITLE
Footer with links to report bugs, etc

### ISSUE THREAD

**Issue by s-omas** [NCAR/music-box-interactive#99]
contain links for:
“About”, “Developers”, “Report a bug”, “Sponsors”, “Why MusicBox”, “Integrations”, “Blog”, “Help Center”, “How to use”, “Watch the Demo”, “News”.

**Comment by s-omas** [comment]
bootstrap example footer: https://getbootstrap.com/docs/4.1/examples/pricing/

**Comment by mattldawson** [comment]
we should probably plan out what each link would point to, and if that page doesn't exist yet figure out what it would contain/look like

**Comment by s-omas** [comment]
We could add one 'about' page which has different sections for things like 'developers', 'sponsors', “Why MusicBox”, “Integrations”, etc.

the links in the footer can just link to the sections of that page

**Comment by mattldawson** [comment]
sounds good - maybe we can just add these sections to the home page, below the 'get started' button?

**Comment by s-omas** [comment]
That sounds good to me

**Comment by AndrewJConley** [comment]
“About”
"Contact us"
“How to use”
“Report a bug - email link”
“Sponsors”
“Developers”
"Partners - UIUC, NCAR, ..."

For later:
“Help Center FAQ's”
“Watch the Demo - URL-links to videos”
"Help Wanted (projects that someone could contribute to)"
“News”
“Components- MICM, CAMP, PHOTO, models, partners”, 
“Why MusicBox”, -- after aerosols
